// <auto-generated />
namespace Mvc_Online_Commercial_Automation.Migrations
{
    using System.CodeDom.Compiler;
    using System.Data.Entity.Migrations;
    using System.Data.Entity.Migrations.Infrastructure;
    using System.Resources;
    
    [GeneratedCode("EntityFramework.Migrations", "6.5.1")]
    public sealed partial class cargotrackings : IMigrationMetadata
    {
        private readonly ResourceManager Resources = new ResourceManager(typeof(cargotrackings));
        
        string IMigrationMetadata.Id
        {
            get { return "202507141549388_cargotrackings"; }
        }
        
        string IMigrationMetadata.Source
        {
            get { return Resources.GetString("Source"); }
        }
        
        string IMigrationMetadata.Target
        {
            get { return Resources.GetString("Target"); }
        }
    }
}
